apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-mongo.fullname" . }}-secret
  labels:
    {{- include "my-mongo.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUser | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.auth.database | quote }}
  MONGO_USERNAME: {{ .Values.auth.appUser | quote }}
  MONGO_PASSWORD: {{ .Values.auth.appPassword | quote }}
