services:
  mongo:
    image: mongo:8
    container_name: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      retries: 5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: mohammedbahr/depi-project-backend
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    env_file: .env
    ports:
      - "5000:5000"

  frontend:
    image: mohammedbahr/depi-project-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:
