sonar.organization=mohammed-bahr
sonar.projectKey=c14b36095f2f55d0d98048caeb4fb4826745fa6e

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src
