sonar.organization=mohammed-bahr
sonar.projectKey=Mohammed-Bahr_AutoScaling-Ecommerce

sonar.sources=backend,frontend/src
sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
