# FROM node:20-alpine AS builder

# WORKDIR /usr/src/app

# COPY package*.json ./

# RUN npm install

# COPY . .

# FROM node:20-alpine

# WORKDIR /usr/src/app

# COPY package*.json ./

# RUN npm install --omit=dev && npm cache clean --force

# COPY --from=builder /usr/src/app/backend ./backend
# # COPY --from=builder /usr/src/app/uploads ./uploads

# EXPOSE 5000

# CMD ["node", "backend/index.js"]
#
# ------------------------------------------------------------------------

FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --omit=dev && npm cache clean --force

# Copy everything directly from the builder stage's workdir
COPY --from=builder /usr/src/app .

EXPOSE 5000

# Since the context is the backend folder, index.js is at the root level
CMD ["node", "index.js"]
