FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --omit=dev && npm cache clean --force

COPY backend/ ./backend/
# COPY uploads/ ./uploads/

EXPOSE 5000

CMD ["node", "backend/index.js"]
