replicaCount: 1

image:
  repository: mongo
  tag: "7.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "my-mongo"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: standard

auth:
  rootUser: "Bahr"
  rootPassword: "1234"
  database: "depi-project"
  appUser: "appuser"
  appPassword: "app1234"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

revisionHistoryLimit: 2
