# `./master-ecommerce/values.yaml`

# 1. Override Frontend Replicas
frontend:
  replicaCount: 2
  image:
    tag: "28947982124"
  ingress:
    host: "ecommerce.local.192.168.1.201.nip.io"
    name: frontend-ingress
# 2. Override Backend Replicas of 
backend:
  replicaCount: 3
  image:
    tag: "latest"
  ingress:
    host: "ecommerce.local.192.168.1.201.nip.io"
