apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  JWT_SECRET: YWJhYzEyYWZzZGtqbGFkZg==

# apiVersion: v1
# kind: Secret
# metadata:
#   name: ecommerce-secrets
# type: Opaque
# data:
#   JWT_SECRET: YWJhYzEyYWZzZGtqbGFkZg==
