apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}-deployment
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "backend.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: MONGO_URI
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secret
                  key: JWT_SECRET
